import JSZip from "jszip";
import { ProductBlueprint } from "@/lib/types/blueprint";

export async function generateProjectZip(blueprint: ProductBlueprint): Promise<Blob> {
  const zip = new JSZip();

  const slug = blueprint.projectTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-");

  // 1. README.md
  const readmeContent = `# ${blueprint.projectTitle} - Starter Repository
> ${blueprint.tagline}

Auto-generated by **ScopePilot AI**

## 🚀 Quick Setup

### 1. Start Infrastructure (PostgreSQL & Redis)
\`\`\`bash
docker compose up -d
\`\`\`

### 2. Install Dependencies & Push Database Schema
\`\`\`bash
npm install
npx prisma db push
\`\`\`

### 3. Run Development Server
\`\`\`bash
npm run dev
\`\`\`

## 📚 System Overview
${blueprint.executiveSummary}

## 🎯 Target Audience
${blueprint.targetAudience.map((a) => `- ${a}`).join("\n")}

## 🚀 MVP Deliverables
${blueprint.mvpScope.map((s) => `- [ ] ${s}`).join("\n")}
`;
  zip.file("README.md", readmeContent);

  // 2. docker-compose.yml
  if (blueprint.codeArtifacts?.dockerCompose) {
    zip.file("docker-compose.yml", blueprint.codeArtifacts.dockerCompose);
  }

  // 3. prisma/schema.prisma
  if (blueprint.codeArtifacts?.prismaSchema) {
    const prismaFolder = zip.folder("prisma");
    prismaFolder?.file("schema.prisma", blueprint.codeArtifacts.prismaSchema);
  }

  // 4. .env.example
  const envExample = `# Database Connection
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/${slug.replace(/-/g, "_")}"

# Cache & Message Broker
REDIS_URL="redis://localhost:6379"

# AI & APIs (Optional)
GEMINI_API_KEY=""
OPENAI_API_KEY=""
RESEND_API_KEY=""
`;
  zip.file(".env.example", envExample);

  // 5. package.json scaffold
  const packageJson = {
    name: slug,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      "db:push": "prisma db push",
      "db:studio": "prisma studio"
    },
    dependencies: {
      next: "^15.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "@prisma/client": "^6.0.0"
    },
    devDependencies: {
      prisma: "^6.0.0",
      typescript: "^5.0.0",
      "@types/node": "^20.0.0",
      "@types/react": "^19.0.0",
      tailwindcss: "^4.0.0"
    }
  };
  zip.file("package.json", JSON.stringify(packageJson, null, 2));

  // 6. api-spec.json
  if (blueprint.codeArtifacts?.apiEndpoints) {
    zip.file("api-spec.json", JSON.stringify(blueprint.codeArtifacts.apiEndpoints, null, 2));
  }

  // 7. full-specification.json
  zip.file("product-blueprint.json", JSON.stringify(blueprint, null, 2));

  return await zip.generateAsync({ type: "blob" });
}

export function triggerDownloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
